export default theme => ({
  wrapper: {
    height: '200px',
    width: '100%',
    '&:hover .description-wrapper': {
      display: 'flex',
    },
    '&:hover .label-wrapper': {
      display: 'none',
    },
  },
  layer: {
    width: '100%',
    height: '100%',
    background: 'linear-gradient(134.79deg, rgba(255,255,255,0.26) 0%, #E6CFC0 100%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  label: {
    fontSize: '24px',
    fontWeight: '500',
    lineHeight: '36px',
    textAlign: 'center',
    textTransform: 'capitalize',
  },
  line: {
    minWidth: '225px',
    background: '#BCE2C9',
    height: '3px',
  },
  descriptionWrapper: {
    background: 'linear-gradient(180deg, rgba(110,115,117,0.5) 0%, #2E3537 100%)',
    display: 'none',
    width: '100%',
    height: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    padding: '24px 16px',
  },
  descriptionLabel: {
    fontSize: '16px',
    textTransform: 'capitalize',
    marginBottom: '24px',
    fontWeight: '300',
    textAlign: 'center',
    color: '#fff',
    lineHeight: '20px',
  },
  description: {
    color: '#fff',
    fontSize: '14px',
    fontWeight: '300',
    overflow: 'hidden',
    display: '-webkit-box',
    '-webkit-line-clamp': 4,
    '-webkit-box-orient': 'vertical',
    maxHeight: '64px',
    lineHeight: '16px',
  },
  chooseBtn: {
    position: 'absolute',
    bottom: '24px',
    color: '#BCE2C9',
    width: '175px',
    textAlign: 'center',
    fontSize: '20px',
    fontWeight: '500',
    borderBottom: '2px solid #88816C',
    paddingBottom: '10px',
    borderRadius: 'unset',
    textTransform: 'capitalize',
    cursor: 'pointer',
    textDecoration: 'none',
    '&:hover': {
      textDecoration: 'none',
    },
  },
});
